"use client";

import Image from "next/image";

import { MoreHorizontal, ThumbsUp, MessageCircle, Repeat2, Send } from "lucide-react";

import ProfileImage from "@/public/ProfileImg.png";

type LinkedInPostUIProps = {
    // linkedinPost: {
    //     authorName: string;
    //     authorTitle: string;
    //     content: string;
    //     link?: string;
    //     // impressions: number;
    // }
    linkedInPost: string;
}

export default function LinkedInPostMockup({ linkedInPost }: LinkedInPostUIProps) {
  return (
    <div className="max-w-xl mx-auto mt-10 bg-white dark:bg-zinc-900 rounded-2xl shadow-md border border-zinc-200 dark:border-zinc-800 p-4">

      {/* Header */}
      <div className="flex items-start justify-between">
        <div className="flex gap-3">
            <Image
                src={ProfileImage} 
                height={12}
                width={12}
                alt="profile-pic"
                className="w-12 h-12 rounded-full"            
            />
          {/* <img
            src="/profile.jpg"
            alt="profile"
            className="w-12 h-12 rounded-full object-cover"
          /> */}
          <div>
            <h3 className="font-semibold text-sm text-zinc-900 dark:text-white">
              Sheikh Faraz
            </h3>
            <p className="text-xs text-zinc-500">
              Web Developer | MERN Stack | TypeScript
            </p>
            <p className="text-xs text-zinc-400">-- ago •</p>
          </div>
        </div>

        <MoreHorizontal className="w-5 h-5 text-zinc-500 cursor-pointer" />
      </div>

      {/* Content */}
      <div className="mt-4 text-sm text-zinc-800 dark:text-zinc-200 space-y-3">
        {/* <p>Just updated my portfolio!</p> */}

        {/* <p>
          Open to feedback, suggestions, and collaboration opportunities. If
          you&apos;re planning a project, let&apos;s discuss and bring it to life!
        </p> */}

        {/* content shown generated by the AI */}
        <p className="whitespace-pre-line text-sm">
            {linkedInPost ? linkedInPost : "You haven't generated a LinkedIn post yet. Use AI to create one!"}
        </p>

        {/* <a
          href="#"
          className="text-blue-600 hover:underline break-all"
        >
          https://lnkd.in/ddrqUVRy
        </a> */}
      </div>

      {/* Stats */}
      <div className="mt-4 text-xs text-zinc-500">
        -- impressions
      </div>

      {/* Divider */}
      <div className="my-3 border-t border-zinc-200 dark:border-zinc-800" />

      {/* Actions */}
      <div className="flex justify-between text-zinc-600 dark:text-zinc-400 text-sm">
        <Action icon={<ThumbsUp size={18} />} label="Like" />
        <Action icon={<MessageCircle size={18} />} label="Comment" />
        <Action icon={<Repeat2 size={18} />} label="Repost" />
        <Action icon={<Send size={18} />} label="Send" />
      </div>
    </div>
  );
}

function Action({ icon, label }: { icon: React.ReactNode; label: string }) {
  return (
    <button className="flex items-center gap-2 hover:bg-zinc-100 dark:hover:bg-zinc-800 px-3 py-2 rounded-lg transition">
      {icon}
      <span>{label}</span>
    </button>
  );
}